name: Deploy Combined Sites to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Build the portfolio site
      - name: Checkout Portfolio Source Repository
        uses: actions/checkout@v3
        with:
          path: portfolio-repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('portfolio-repo/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Portfolio Dependencies
        working-directory: ./portfolio-repo
        run: pnpm install

      - name: Build Portfolio App
        working-directory: ./portfolio-repo
        run: pnpm run build

      # Build the blog site
      - name: Checkout Blog Source Repository
        uses: actions/checkout@v3
        with:
          repository: hallucinogenizer/personal-tailwind-nextjs-blog
          ref: rohan
          path: blog-repo

      - name: Setup Yarn Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('blog-repo/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Blog Dependencies
        working-directory: ./blog-repo
        run: yarn install

      - name: Build Blog
        working-directory: ./blog-repo
        run: yarn build

      # Clone the GitHub Pages repository to prepare it for deployment
      - name: Clone GitHub Pages Repository
        run: |
          git clone https://${{ secrets.DEPLOY_TOKEN }}@github.com/hallucinogenizer/hallucinogenizer.github.io.git deploy-repo

      # Prepare the combined output in the deploy repository
      - name: Prepare Combined Output
        run: |
          # Remove existing content (except .git directory)
          find deploy-repo -mindepth 1 -not -path "deploy-repo/.git*" -delete

          # Copy portfolio build output to root
          cp -r portfolio-repo/dist/* deploy-repo/

          # Copy blog build output to blog directory
          mkdir -p deploy-repo/blog
          cp -r blog-repo/out/* deploy-repo/blog/

      # Deploy using JamesIves action
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy-repo
          repository-name: hallucinogenizer/hallucinogenizer.github.io
          branch: main
          token: ${{ secrets.DEPLOY_TOKEN }}
