name: Deploy Portfolio with Existing Blog via Manual Git

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # --- Build the portfolio site ---
      - name: Checkout Portfolio Source Repository
        uses: actions/checkout@v3
        with:
          path: portfolio-repo # Checks out the repo containing this workflow

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('portfolio-repo/**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Portfolio Dependencies
        working-directory: ./portfolio-repo
        run: pnpm install

      - name: Build Portfolio App
        working-directory: ./portfolio-repo
        run: pnpm run build # Output goes to portfolio-repo/dist

      # --- Prepare and Deploy Manually ---
      - name: Clone Target GitHub Pages Repository
        run: |
          git clone https://x-access-token:${{ secrets.DEPLOY_TOKEN }}@github.com/hallucinogenizer/hallucinogenizer.github.io.git deploy-repo
        # Ensure DEPLOY_TOKEN has repo scope permissions for hallucinogenizer.github.io

      - name: Copy Existing Blog Content into Portfolio Dist
        run: |
          echo "Copying existing blog content from deploy-repo/blog to portfolio-repo/dist/blog"
          # Create the target blog directory within dist if it doesn't exist
          mkdir -p portfolio-repo/dist/blog
          # Copy content; use || true to prevent failure if source /blog doesn't exist
          cp -r deploy-repo/blog/* portfolio-repo/dist/blog/ || echo "No existing blog content found in deploy-repo/blog or copy failed. Continuing."
          echo "Contents of portfolio-repo/dist after adding blog:"
          ls -R portfolio-repo/dist

      - name: Deploy Updated Dist to GitHub Pages Repo
        run: |
          cd deploy-repo
          echo "Configuring git user..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          echo "Removing old content (keeping .git)..."
          # Use find to delete everything except the .git directory
          find . -mindepth 1 -not -path "./.git*" -delete

          echo "Copying new combined content from portfolio-repo/dist..."
          cp -r ../portfolio-repo/dist/* .

          echo "Checking for changes..."
          git status

          echo "Adding changes..."
          git add .

          echo "Committing changes..."
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Deploy portfolio with existing blog content - $(date)"
            echo "Pushing changes..."
            git push origin main # Make sure 'main' is your target branch
          fi
        env:
          GIT_TOKEN: ${{ secrets.DEPLOY_TOKEN }} # Often not needed directly for https push with token in URL, but doesn't hurt
